name: Build
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6 # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      
      - name: Run
        run: make build

      - name: Checkout target
        run: | 
          git checkout gh-pages
          git merge master
          git pull origin gh-pages

      - id: commit 
        name: Commit
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "actions@github.com"
            git config pull.rebase false
            git status
            git pull origin $GITHUB_REF
            git add ./
            git commit -m "Build site" && git push || true
        shell: bash
