name: Build
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Run
        run: make build

      - name: Checkout target
        run: | 
          git checkout gh-pages
          git merge master
          git pull origin gh-pages

      - id: commit 
        name: Commit
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "actions@github.com"
            git config pull.rebase false
            git status
            git pull origin $GITHUB_REF
            git add ./
            git commit -m "Build site" && git push || true
        shell: bash
