name: Build
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - id: install-pipenv
        name: Install pipenv
        run: |
          python -m pip install --upgrade --no-cache-dir pip
          python -m pip install --no-cache-dir pipenv
        shell: bash

      - id: cache-pipenv
        name: Cache pipenv
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - id: sync-pipfile
        name: Sync pipfile
        run: pipenv sync
        shell: bash
      
      - name: Run
        run: make build

      - name: Checkout target
        run: | 
          git checkout gh-pages
          git merge master
          git pull origin gh-pages

      - id: commit 
        name: Commit
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "actions@github.com"
            git config pull.rebase false
            git status
            git pull origin $GITHUB_REF
            git add ./
            git commit -m "Build site" && git push || true
        shell: bash
